"""photomodel_commentmodel add editor_username

Revision ID: 4d9a03585c27
Revises: 7d1408c45fd4
Create Date: 2024-02-22 23:18:38.211496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9a03585c27'
down_revision: Union[str, None] = '7d1408c45fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('editor_username', sa.String(length=255), nullable=True))
    op.drop_constraint('comments_editor_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'editor_id')
    op.add_column('photos', sa.Column('editor_username', sa.String(length=255), nullable=True))
    op.drop_constraint('photos_editor_id_fkey', 'photos', type_='foreignkey')
    op.drop_column('photos', 'editor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('editor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('photos_editor_id_fkey', 'photos', 'users', ['editor_id'], ['id'])
    op.drop_column('photos', 'editor_username')
    op.add_column('comments', sa.Column('editor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_editor_id_fkey', 'comments', 'users', ['editor_id'], ['id'])
    op.drop_column('comments', 'editor_username')
    # ### end Alembic commands ###
