"""photomodel and commentmodel add editor_id

Revision ID: 7d1408c45fd4
Revises: a9cee740f5d3
Create Date: 2024-02-22 19:51:47.951604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1408c45fd4'
down_revision: Union[str, None] = 'a9cee740f5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('editor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'comments', 'users', ['editor_id'], ['id'])
    op.add_column('photos', sa.Column('editor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'photos', 'users', ['editor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'editor_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'editor_id')
    # ### end Alembic commands ###
