"""bugfix user and blacklist

Revision ID: aa06e1e7986e
Revises: 50d069dd9f67
Create Date: 2024-02-18 22:03:17.630451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa06e1e7986e'
down_revision: Union[str, None] = '50d069dd9f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist', sa.Column('token', sa.String(length=255), nullable=True))
    op.drop_column('blacklist', 'access_token')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('blacklist', sa.Column('access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blacklist', 'token')
    # ### end Alembic commands ###
